//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QWERTY_s_1_ex_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartsToRepair
    {
        public int idRepair { get; set; }
        public int idpart { get; set; }
        public int count { get; set; }
    
        public virtual DevicePart DevicePart { get; set; }
        public virtual Repair Repair { get; set; }
    }
}
